version: '3.8'

services:
  backend:
    build: ./backend
    container_name: loyalty-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
      - backend_db:/app/cards.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: loyalty-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  backend_uploads:
  backend_db:
